sharding:
  jdbc:
    datasource:
      names: ds_master_0,ds_master_0_slave_0,ds_master_0_slave_1,ds_master_1,ds_master_1_slave_0,ds_master_1_slave_1
      ds_master_0:
        type: org.apache.commons.dbcp.BasicDataSource
        driver-class-name: net.sf.log4jdbc.DriverSpy
        url: jdbc:log4jdbc:mysql://localhost:3306/demo_ds_master_0?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123
      ds_master_0_slave_0:
        type: org.apache.commons.dbcp.BasicDataSource
        driver-class-name: net.sf.log4jdbc.DriverSpy
        url: jdbc:log4jdbc:mysql://localhost:3306/demo_ds_master_0_slave_0?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123
      ds_master_0_slave_1:
        type: org.apache.commons.dbcp.BasicDataSource
        driver-class-name: net.sf.log4jdbc.DriverSpy
        url: jdbc:log4jdbc:mysql://localhost:3306/demo_ds_master_0_slave_1?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123
      ds_master_1:
        type: org.apache.commons.dbcp.BasicDataSource
        driver-class-name: net.sf.log4jdbc.DriverSpy
        url: jdbc:log4jdbc:mysql://localhost:3306/demo_ds_master_1?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123
      ds_master_1_slave_0:
        type: org.apache.commons.dbcp.BasicDataSource
        driver-class-name: net.sf.log4jdbc.DriverSpy
        url: jdbc:log4jdbc:mysql://localhost:3306/demo_ds_master_1_slave_0?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123
      ds_master_1_slave_1:
        type: org.apache.commons.dbcp.BasicDataSource
        driver-class-name: net.sf.log4jdbc.DriverSpy
        url: jdbc:log4jdbc:mysql://localhost:3306/demo_ds_master_1_slave_1?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123
    config:
      sharding:
        default-database-strategy:
          inline:
            sharding-column: user_id
            algorithm-expression: ds_${user_id % 2}
        tables:
          t_order:
            actual-data-nodes: ds_${0..1}.t_order_${0..1}
            table-strategy:
              inline:
                sharding-column: order_id
                algorithm-expression: t_order_${order_id % 2}
            key-generator-column-name: order_id
          t_order_item:
            actual-data-nodes: ds_${0..1}.t_order_item_${0..1}
            table-strategy:
              inline:
                sharding-column: order_id
                algorithm-expression: t_order_item_${order_id % 2}
            key-generator-column-name: order_item_id
        master-slave-rules:
          ds_0:
            master-data-source-name: ds_master_0
            slave-data-source-names: ds_master_0_slave_0, ds_master_0_slave_1
          ds_1:
            master-data-source-name: ds_master_1
            slave-data-source-names: ds_master_1_slave_0, ds_master_1_slave_1
